image: atlassian/default-image:3

pipelines:
  branches:
    dev:
      - step:
          name: Build and Push Docker Image
          script:
            - docker build -t ${DOCKER_USERNAME}/patungan-backend-go:latest .
            - echo ${DOCKER_PASSWORD} | docker login --username ${DOCKER_USERNAME} --password ${DOCKER_PASSWORD}
            - docker push ${DOCKER_USERNAME}/patungan-backend-go:latest
          services:
            - docker
          caches:
            - docker

    main:
      - step:
          name: Deploy to server
          deployment: production
          script:
            - pipe: atlassian/ssh-run:0.4.0
              variables:
                SSH_USER: $SERVER_USER
                SERVER: $SERVER_IP
                SSH_KEY: $SSH_KEY
                COMMAND: |
                  echo "Pulling latest docker image from Docker Hub ..."
                  docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
                  docker pull $DOCKER_USERNAME/patungan-backend-go:latest
                  echo "Stopping and removing old container ..."
                  docker stop my-backend || true
                  docker rm my-backend || true
                  echo "Removing old untagged images ..."
                  docker images --filter "dangling=true" -q | xargs -r docker rmi
                  echo "Running new container ..."
                  docker run --name my-backend -e USERNAME="${DB_USERNAME}" -e PASSWORD="${DB_PASSWORD}" -e HOST="${DB_HOST}" -e PORT="${DB_PORT}" -e DBNAME="${DB_NAME}" -e GEMINIKEY=${GEMINI_KEY} --network my-network -p 9090:9090 -d $DOCKER_USERNAME/patungan-backend-go:latest
